gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:latest
  volume_driver: convoy-nfs
  volumes:
  - gitlab-etc:/etc/gitlab
  - gitlab-log:/var/log/gitlab
  - gitlab-opt:/var/opt/gitlab
gitlab-server:
  ports:
  - 2235:22/tcp
  - 8082:80/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: git.mahyuddin.cf
  image: gitlab/gitlab-ce:latest
  volume_driver: convoy-nfs
  volumes_from:
  - gitlab-data

