gitlab-data:
  scale: 1
  retain_ip: true
gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

